"use client";

import { useMemo, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ArrowUpRight, Banknote, Bell, Brain, CalendarDays, Check, ChevronRight, CircleDollarSign, Command, Dumbbell, Flame, HeartPulse, Home, Moon, Plus, Search, Settings, ShieldCheck, Sparkles, SunMedium, UserRound, WalletCards, Zap } from "lucide-react";
import { Bar, BarChart, ResponsiveContainer, Tooltip, XAxis } from "recharts";
import { Checkbox } from "@/components/ui/checkbox";

type Routine = { id:number; time:string; title:string; meta:string; done:boolean };
const spendData=[{day:"Thu",value:28},{day:"Fri",value:44},{day:"Sat",value:82},{day:"Sun",value:36},{day:"Mon",value:58},{day:"Tue",value:22},{day:"Today",value:31}];
const initialRoutines:Routine[]=[
  {id:1,time:"06:30",title:"Morning activation",meta:"Hydrate · sunlight · mobility",done:true},
  {id:2,time:"07:15",title:"Deep work block",meta:"90 minutes · priority one",done:true},
  {id:3,time:"12:30",title:"Fuel & reset",meta:"Protein lunch · 10 min walk",done:false},
  {id:4,time:"17:45",title:"Upper body strength",meta:"Push focus · progressive overload",done:false},
  {id:5,time:"21:30",title:"Night shutdown",meta:"Skincare · reflect · prepare",done:false},
];
const nav=[{label:"Command",icon:Home,href:"#command"},{label:"Wealth",icon:WalletCards,href:"#wealth"},{label:"Blueprint",icon:CalendarDays,href:"#blueprint"},{label:"Ascension",icon:Sparkles,href:"#ascension"}];

function Panel({children,className=""}:{children:React.ReactNode;className?:string}){return <section className={`panel ${className}`}>{children}</section>}
function ProgressBar({value,blue=false}:{value:number;blue?:boolean}){return <div className="h-2 overflow-hidden rounded-full bg-white/[0.06]" role="progressbar" aria-valuenow={value} aria-valuemin={0} aria-valuemax={100}><motion.div initial={{width:0}} animate={{width:`${value}%`}} transition={{duration:.8,ease:"easeOut"}} className={`h-full rounded-full ${blue?"bg-[#37a8ff] shadow-[0_0_18px_rgba(55,168,255,.5)]":"bg-[#36f4a2] shadow-[0_0_18px_rgba(54,244,162,.45)]"}`}/></div>}

export default function HomePage(){
  const [active,setActive]=useState("Command"); const [routines,setRoutines]=useState(initialRoutines); const [expense,setExpense]=useState(""); const [expenses,setExpenses]=useState<string[]>([]); const [protein,setProtein]=useState(118); const [water,setWater]=useState(6); const [note,setNote]=useState(""); const [saved,setSaved]=useState(false);
  const completed=routines.filter(i=>i.done).length; const dailyProgress=Math.round(completed/routines.length*100); const date=useMemo(()=>new Intl.DateTimeFormat("en",{weekday:"long",month:"long",day:"numeric"}).format(new Date()),[]);
  const toggle=(id:number)=>setRoutines(c=>c.map(i=>i.id===id?{...i,done:!i.done}:i));
  const addExpense=()=>{const clean=expense.trim();if(!clean)return;setExpenses(c=>[clean,...c]);setExpense("")};
  return <div className="min-h-screen bg-[#070a0f] text-slate-100 selection:bg-emerald-400/30">
    <div className="ambient ambient-one"/><div className="ambient ambient-two"/>
    <aside className="fixed inset-y-0 left-0 z-40 hidden w-[244px] border-r border-white/[0.06] bg-[#080c12]/90 px-5 py-6 backdrop-blur-xl lg:flex lg:flex-col">
      <a href="#command" className="flex items-center gap-3 px-2" aria-label="Ascend OS home"><div className="grid h-9 w-9 place-items-center rounded-xl border border-emerald-300/20 bg-emerald-300/10 text-emerald-300 shadow-[0_0_24px_rgba(54,244,162,.12)]"><Command size={18}/></div><div><div className="text-[15px] font-semibold tracking-wide text-white">ASCEND <span className="text-emerald-300">OS</span></div><div className="text-[10px] uppercase tracking-[0.22em] text-slate-600">Personal system</div></div></a>
      <nav className="mt-12 space-y-2" aria-label="Primary navigation">{nav.map(item=>{const Icon=item.icon,selected=active===item.label;return <a key={item.label} href={item.href} onClick={()=>setActive(item.label)} className={`group flex h-11 items-center gap-3 rounded-xl px-3 text-sm transition ${selected?"bg-white/[0.06] text-white":"text-slate-500 hover:bg-white/[0.035] hover:text-slate-200"}`}><span className={selected?"text-emerald-300":"text-slate-600 group-hover:text-slate-300"}><Icon size={18}/></span>{item.label}{selected&&<motion.span layoutId="nav-dot" className="ml-auto h-1.5 w-1.5 rounded-full bg-emerald-300 shadow-[0_0_10px_#36f4a2]"/>}</a>})}</nav>
      <div className="mt-auto rounded-2xl border border-white/[0.06] bg-white/[0.025] p-4"><div className="mb-3 flex items-center justify-between"><span className="text-xs font-medium text-slate-400">Weekly ascent</span><span className="text-xs font-semibold text-emerald-300">+12%</span></div><ProgressBar value={74}/><p className="mt-3 text-xs leading-relaxed text-slate-600">You’re building momentum. Keep the standard today.</p></div>
      <button className="mt-4 flex items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm text-slate-500 transition hover:bg-white/[0.04] hover:text-white"><Settings size={17}/> Settings</button>
    </aside>
    <main className="relative z-10 pb-28 lg:ml-[244px] lg:pb-12">
      <header className="sticky top-0 z-30 flex h-[72px] items-center justify-between border-b border-white/[0.055] bg-[#070a0f]/80 px-5 backdrop-blur-xl sm:px-8 lg:px-10"><div className="flex items-center gap-3 lg:hidden"><div className="grid h-9 w-9 place-items-center rounded-xl bg-emerald-300/10 text-emerald-300"><Command size={18}/></div><span className="text-sm font-semibold">ASCEND OS</span></div><div className="hidden items-center gap-2 text-xs text-slate-500 lg:flex"><span className="h-2 w-2 rounded-full bg-emerald-300 shadow-[0_0_9px_#36f4a2]"/> All systems aligned</div><div className="flex items-center gap-2"><button className="icon-button" aria-label="Search"><Search size={17}/></button><button className="icon-button" aria-label="Notifications"><Bell size={17}/><span className="absolute right-2 top-2 h-1.5 w-1.5 rounded-full bg-blue-400"/></button><button className="ml-1 grid h-9 w-9 place-items-center rounded-xl border border-white/10 bg-gradient-to-br from-slate-700 to-slate-900 text-slate-300" aria-label="Profile"><UserRound size={17}/></button></div></header>
      <div className="mx-auto max-w-[1480px] px-5 py-7 sm:px-8 lg:px-10 lg:py-9">
        <section id="command" className="scroll-mt-24">
          <div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-2 text-xs font-medium uppercase tracking-[0.18em] text-slate-600">{date}</p><h1 className="text-3xl font-semibold tracking-[-0.045em] text-white sm:text-4xl">Good morning.</h1><p className="mt-2 text-sm text-slate-500">Protect the momentum. Win the next block.</p></div><button onClick={()=>document.getElementById("blueprint")?.scrollIntoView({behavior:"smooth"})} className="primary-button self-start sm:self-auto"><Zap size={15} fill="currentColor"/> Focus next block</button></div>
          <div className="grid gap-4 xl:grid-cols-[1.05fr_1.05fr_.9fr]">
            <Panel className="relative overflow-hidden p-5 sm:p-6"><div className="card-shine"/><div className="relative flex h-full min-h-[184px] flex-col justify-between"><div className="flex items-start justify-between"><div><p className="eyebrow">Available today</p><p className="mt-3 text-4xl font-semibold tracking-[-0.05em] text-white">RM 68<span className="text-xl text-slate-600">.40</span></p></div><div className="icon-well text-emerald-300"><CircleDollarSign size={19}/></div></div><div><div className="mb-2 flex justify-between text-xs"><span className="text-slate-500">Daily allowance</span><span className="text-slate-300">46% used</span></div><ProgressBar value={46}/><p className="mt-3 text-xs text-slate-600">RM 58.60 spent of RM 127.00</p></div></div></Panel>
            <Panel className="p-5 sm:p-6"><div className="flex h-full min-h-[184px] flex-col justify-between"><div className="flex items-start justify-between"><div><p className="eyebrow">Next routine block</p><p className="mt-3 text-2xl font-semibold tracking-[-0.035em] text-white">Fuel & reset</p><p className="mt-2 text-sm text-slate-500">12:30 — in 42 minutes</p></div><div className="icon-well text-blue-400"><CalendarDays size={19}/></div></div><button onClick={()=>toggle(3)} className="flex items-center justify-between rounded-xl border border-white/[0.06] bg-white/[0.025] px-4 py-3 text-sm text-slate-300 transition hover:border-blue-400/20 hover:bg-blue-400/[0.04]"><span>Protein lunch · 10 min walk</span><ChevronRight size={16} className="text-slate-600"/></button></div></Panel>
            <Panel className="flex min-h-[220px] items-center justify-between gap-4 p-5 sm:p-6 xl:min-h-[184px]"><div><p className="eyebrow">Daily completion</p><p className="mt-4 text-xl font-semibold text-white">On pace</p><p className="mt-2 max-w-[145px] text-sm leading-relaxed text-slate-500">{completed} of {routines.length} core blocks secured.</p></div><div className="relative grid h-32 w-32 shrink-0 place-items-center"><svg className="h-full w-full -rotate-90" viewBox="0 0 120 120" aria-label={`${dailyProgress}% daily progress`}><circle cx="60" cy="60" r="50" fill="none" stroke="rgba(255,255,255,.06)" strokeWidth="8"/><motion.circle cx="60" cy="60" r="50" fill="none" stroke="url(#ring)" strokeLinecap="round" strokeWidth="8" strokeDasharray="314" initial={{strokeDashoffset:314}} animate={{strokeDashoffset:314-314*dailyProgress/100}} transition={{duration:.8}}/><defs><linearGradient id="ring"><stop stopColor="#36f4a2"/><stop offset="1" stopColor="#37a8ff"/></linearGradient></defs></svg><div className="absolute text-center"><span className="block text-2xl font-semibold text-white">{dailyProgress}%</span><span className="text-[10px] uppercase tracking-widest text-slate-600">complete</span></div></div></Panel>
          </div>
        </section>
        <section id="wealth" className="mt-5 scroll-mt-24 grid gap-5 xl:grid-cols-[1.35fr_.65fr]">
          <Panel className="overflow-hidden p-5 sm:p-6"><div className="mb-6 flex items-center justify-between"><div><p className="eyebrow">Wealth engine</p><h2 className="section-title">Seven-day spend</h2></div><div className="rounded-lg border border-white/[0.06] px-3 py-2 text-xs text-slate-500">RM 301 total</div></div><div className="h-[220px] w-full"><ResponsiveContainer width="100%" height="100%"><BarChart data={spendData} margin={{top:10,right:0,left:0,bottom:0}}><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{fill:"#667085",fontSize:11}}/><Tooltip cursor={{fill:"rgba(255,255,255,.025)"}} contentStyle={{background:"#10161f",border:"1px solid rgba(255,255,255,.08)",borderRadius:12,color:"white"}} formatter={value=>[`RM ${value}`,"Spend"]}/><Bar dataKey="value" fill="#263242" radius={[7,7,2,2]} activeBar={{fill:"#36f4a2"}}/></BarChart></ResponsiveContainer></div></Panel>
          <Panel className="p-5 sm:p-6"><div className="flex items-center justify-between"><div><p className="eyebrow">Quick capture</p><h2 className="section-title">Add expense</h2></div><div className="icon-well text-emerald-300"><Banknote size={18}/></div></div><form onSubmit={e=>{e.preventDefault();addExpense()}} className="mt-8"><label htmlFor="expense" className="mb-2 block text-xs font-medium text-slate-500">What did you spend?</label><div className="flex gap-2"><input id="expense" value={expense} onChange={e=>setExpense(e.target.value)} className="field h-12 min-w-0 flex-1" placeholder="Lunch 18.50"/><button className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-emerald-300 text-[#07110c] transition hover:bg-emerald-200 active:scale-95" aria-label="Add expense"><Plus size={20}/></button></div></form><AnimatePresence initial={false}>{expenses.slice(0,2).map(item=><motion.div key={item} initial={{opacity:0,y:-8}} animate={{opacity:1,y:0}} exit={{opacity:0}} className="mt-3 flex items-center justify-between rounded-xl bg-white/[0.03] px-4 py-3 text-sm"><span className="text-slate-300">{item}</span><Check size={15} className="text-emerald-300"/></motion.div>)}</AnimatePresence>{expenses.length===0&&<div className="mt-5 rounded-xl border border-dashed border-white/[0.07] px-4 py-4 text-center text-xs text-slate-600">Use natural language. Amount is recognized instantly.</div>}</Panel>
        </section>
        <section id="blueprint" className="mt-5 scroll-mt-24 grid gap-5 xl:grid-cols-[1.25fr_.75fr]">
          <Panel className="p-5 sm:p-6"><div className="mb-7 flex items-center justify-between"><div><p className="eyebrow">The blueprint</p><h2 className="section-title">Today’s timeline</h2></div><span className="text-xs text-slate-600">{completed}/{routines.length} complete</span></div><div className="space-y-1">{routines.map((item,index)=><motion.div layout key={item.id} className="group grid grid-cols-[48px_24px_1fr] items-start gap-3 rounded-xl px-2 py-3 transition hover:bg-white/[0.025] sm:grid-cols-[58px_28px_1fr_auto]"><span className="pt-0.5 text-xs tabular-nums text-slate-600">{item.time}</span><div className="relative flex justify-center"><Checkbox checked={item.done} onCheckedChange={()=>toggle(item.id)} aria-label={`Mark ${item.title} complete`} className="h-5 w-5 rounded-md border-white/15 data-[state=checked]:border-emerald-300 data-[state=checked]:bg-emerald-300 data-[state=checked]:text-[#06100b]"/>{index<routines.length-1&&<span className="absolute top-7 h-9 w-px bg-white/[0.06]"/>}</div><button onClick={()=>toggle(item.id)} className="min-w-0 text-left"><motion.span animate={{color:item.done?"#64748b":"#e2e8f0"}} className={`block text-sm font-medium ${item.done?"line-through decoration-slate-700":""}`}>{item.title}</motion.span><span className="mt-1 block truncate text-xs text-slate-600">{item.meta}</span></button><span className={`hidden rounded-lg px-2 py-1 text-[10px] uppercase tracking-wider sm:block ${item.done?"bg-emerald-300/10 text-emerald-300":"bg-white/[0.03] text-slate-600"}`}>{item.done?"done":"queued"}</span></motion.div>)}</div></Panel>
          <Panel className="p-5 sm:p-6"><div className="flex items-center justify-between"><div><p className="eyebrow">Core habits</p><h2 className="section-title">Streaks</h2></div><Flame size={20} className="text-orange-400" fill="currentColor"/></div><div className="mt-7 space-y-3">{[{name:"Training",days:18,icon:Dumbbell},{name:"Deep work",days:12,icon:Brain},{name:"No-spend",days:6,icon:ShieldCheck}].map(h=>{const Icon=h.icon;return <div key={h.name} className="flex items-center gap-3 rounded-2xl border border-white/[0.055] bg-white/[0.022] p-4"><div className="icon-well h-10 w-10 text-slate-400"><Icon size={17}/></div><div className="min-w-0 flex-1"><p className="text-sm font-medium text-slate-200">{h.name}</p><p className="mt-1 text-xs text-slate-600">Personal best in motion</p></div><div className="text-right"><div className="flex items-center justify-end gap-1 text-sm font-semibold text-orange-400"><Flame size={14} fill="currentColor"/>{h.days}</div><span className="text-[10px] text-slate-600">days</span></div></div>})}</div></Panel>
        </section>
        <section id="ascension" className="mt-5 scroll-mt-24"><div className="mb-4 flex items-end justify-between"><div><p className="eyebrow">Ascension protocol</p><h2 className="section-title">Build the next version</h2></div><span className="hidden text-xs text-slate-600 sm:block">Consistency compounds</span></div><div className="grid gap-5 xl:grid-cols-3">
          <Panel className="p-5 sm:p-6"><div className="flex items-center justify-between"><div className="icon-well text-blue-400"><Dumbbell size={18}/></div><span className="text-xs text-slate-600">Physique</span></div><div className="mt-6 flex items-end justify-between"><div><p className="text-sm text-slate-500">Protein intake</p><p className="mt-1 text-3xl font-semibold tracking-tight text-white">{protein}<span className="text-base text-slate-600"> / 160g</span></p></div><span className="text-sm font-medium text-blue-400">{Math.round(protein/160*100)}%</span></div><div className="mt-4"><ProgressBar value={protein/160*100} blue/></div><div className="mt-5 flex gap-2"><button onClick={()=>setProtein(v=>Math.min(160,v+10))} className="secondary-button flex-1"><Plus size={14}/> Add 10g</button><button className="secondary-button px-4" aria-label="View workout"><ArrowUpRight size={15}/></button></div><div className="mt-4 flex items-center justify-between rounded-xl bg-white/[0.025] p-3"><div><p className="text-xs text-slate-500">Next lift</p><p className="mt-1 text-sm text-slate-200">Bench press · 72.5 kg</p></div><span className="rounded-lg bg-blue-400/10 px-2 py-1 text-xs text-blue-400">+2.5</span></div></Panel>
          <Panel className="p-5 sm:p-6"><div className="flex items-center justify-between"><div className="icon-well text-emerald-300"><HeartPulse size={18}/></div><span className="text-xs text-slate-600">Aesthetics</span></div><div className="mt-6"><div className="mb-3 flex items-end justify-between"><div><p className="text-sm text-slate-500">Hydration</p><p className="mt-1 text-2xl font-semibold text-white">{water}<span className="text-sm text-slate-600"> / 8 glasses</span></p></div><button onClick={()=>setWater(v=>Math.min(8,v+1))} className="mini-add"><Plus size={14}/></button></div><ProgressBar value={water/8*100}/></div><div className="mt-6 space-y-3">{[{label:"Morning skincare",icon:SunMedium},{label:"Night skincare",icon:Moon}].map((task,i)=>{const Icon=task.icon;return <label key={task.label} className="flex cursor-pointer items-center gap-3 rounded-xl border border-white/[0.055] p-3.5 text-sm text-slate-300 transition hover:bg-white/[0.025]"><Checkbox defaultChecked={i===0} className="border-white/15 data-[state=checked]:border-emerald-300 data-[state=checked]:bg-emerald-300 data-[state=checked]:text-[#06100b]"/><Icon size={16} className="text-slate-600"/>{task.label}</label>})}</div></Panel>
          <Panel className="p-5 sm:p-6"><div className="flex items-center justify-between"><div className="icon-well text-violet-400"><Brain size={18}/></div><span className="text-xs text-slate-600">Mental diet</span></div><label htmlFor="reflection" className="mt-6 block text-sm font-medium text-slate-300">What expanded you today?</label><p className="mt-1 text-xs text-slate-600">Capture one lesson or comfort-zone win.</p><textarea id="reflection" value={note} onChange={e=>{setNote(e.target.value);setSaved(false)}} className="field mt-4 min-h-[112px] resize-none py-3" placeholder="I learned that…"/><button onClick={()=>note.trim()&&setSaved(true)} className="primary-button mt-3 w-full justify-center">{saved?<><Check size={15}/> Reflection saved</>:<><Sparkles size={15}/> Save reflection</>}</button></Panel>
        </div></section>
        <footer className="mt-8 flex flex-col gap-2 border-t border-white/[0.05] pt-6 text-xs text-slate-700 sm:flex-row sm:items-center sm:justify-between"><span>Ascend OS · Private command center</span><span>Small standards. Extraordinary trajectory.</span></footer>
      </div>
    </main>
    <nav className="fixed inset-x-4 bottom-4 z-50 grid grid-cols-4 rounded-2xl border border-white/[0.08] bg-[#0c1119]/92 p-1.5 shadow-2xl backdrop-blur-2xl lg:hidden" aria-label="Mobile navigation">{nav.map(item=>{const Icon=item.icon,selected=active===item.label;return <a key={item.label} href={item.href} onClick={()=>setActive(item.label)} className={`flex flex-col items-center gap-1 rounded-xl py-2 text-[10px] transition ${selected?"bg-white/[0.06] text-emerald-300":"text-slate-600"}`}><Icon size={18}/><span>{item.label}</span></a>})}</nav>
  </div>
}
