"use client";

import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { ArrowUpRight, Banknote, Bell, BellRing, Brain, CalendarDays, Check, ChevronRight, CircleDollarSign, Cloud, CloudOff, Command, Dumbbell, Edit3, Flame, HeartPulse, Home, LogIn, LogOut, Moon, Plus, RotateCcw, Search, Settings, ShieldCheck, Sparkles, SunMedium, Target, Trash2, TrendingUp, UserRound, Volume2, VolumeX, WalletCards, X, Zap } from "lucide-react";
import { Bar, BarChart, Line, LineChart, ResponsiveContainer, Tooltip, XAxis } from "recharts";
import { Checkbox } from "@/components/ui/checkbox";
import { type ExpenseCategory, type HabitKey, type Routine, useAscendData } from "@/hooks/use-ascend-data";
import { useNotifications } from "@/hooks/use-notifications";

const nav = [{ label: "Command", icon: Home, href: "#command" }, { label: "Wealth", icon: WalletCards, href: "#wealth" }, { label: "Blueprint", icon: CalendarDays, href: "#blueprint" }, { label: "Ascension", icon: Sparkles, href: "#ascension" }];
const habitDetails: Array<{ key: HabitKey; name: string; icon: typeof Dumbbell }> = [{ key: "training", name: "Training", icon: Dumbbell }, { key: "deepWork", name: "Deep work", icon: Brain }, { key: "noSpend", name: "No-spend", icon: ShieldCheck }];
const emptyRoutine = { time: "08:00", title: "", meta: "", days: [0, 1, 2, 3, 4, 5, 6] };
type RoutineDraft = typeof emptyRoutine & { id?: string };
const expenseCategories: ExpenseCategory[] = ["Food", "Transport", "Bills", "Shopping", "Health", "Fun", "Other"];
const weekDays = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

function Panel({ children, className = "" }: { children: ReactNode; className?: string }) { return <section className={`panel ${className}`}>{children}</section>; }
function ProgressBar({ value, blue = false }: { value: number; blue?: boolean }) { const safe = Math.max(0, Math.min(100, value)); return <div className="h-2 overflow-hidden rounded-full bg-white/[0.06]" role="progressbar" aria-valuenow={Math.round(safe)}><motion.div initial={{ width: 0 }} animate={{ width: `${safe}%` }} className={`h-full rounded-full ${blue ? "bg-[#37a8ff] shadow-[0_0_18px_rgba(55,168,255,.5)]" : "bg-[#36f4a2] shadow-[0_0_18px_rgba(54,244,162,.45)]"}`} /></div>; }
const money = (value: number) => new Intl.NumberFormat("en-MY", { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(value);

export default function HomePage() {
  const data = useAscendData();
  const { routines, expenses, lifts, wellness } = data;
  const bodyLogs: Array<{ id: string; weight: number; bodyFat?: number; waist?: number }> = [];
  const [active, setActive] = useState("Command");
  const [expenseInput, setExpenseInput] = useState("");
  const [expenseCategory, setExpenseCategory] = useState<ExpenseCategory>("Food");
  const [routineDraft, setRoutineDraft] = useState<RoutineDraft | null>(null);
  const [liftDraft, setLiftDraft] = useState({ exercise: "Bench press", weight: "72.5", reps: "8" });
  const [bodyDraft, setBodyDraft] = useState({ weight: "", bodyFat: "", waist: "" });
  const [noteDraft, setNoteDraft] = useState(wellness.note);
  const [notice, setNotice] = useState("");
  const [profileOpen, setProfileOpen] = useState(false);
  const [notificationOpen, setNotificationOpen] = useState(false);
  const notifications = useNotifications({
    enabled: wellness.notificationsEnabled,
    sound: wellness.notificationSound,
    onToken: async (pushToken) => data.updateWellness({ pushToken }),
  });
  useEffect(() => setNoteDraft(wellness.note), [wellness.note]);
  const weekday = new Date().getDay();
  const todayRoutines = routines.filter((item) => !item.days || item.days.includes(weekday));
  const completed = todayRoutines.filter((item) => item.done).length;
  const progress = todayRoutines.length ? Math.round(completed / todayRoutines.length * 100) : 0;
  const date = useMemo(() => new Intl.DateTimeFormat("en", { weekday: "long", month: "long", day: "numeric" }).format(new Date()), []);
  const spendData = useMemo(() => Array.from({ length: 7 }, (_, index) => { const day = new Date(); day.setHours(0, 0, 0, 0); day.setDate(day.getDate() - (6 - index)); const end = new Date(day); end.setDate(end.getDate() + 1); return { day: index === 6 ? "Today" : new Intl.DateTimeFormat("en", { weekday: "short" }).format(day), value: expenses.filter((item) => item.createdAt >= day.getTime() && item.createdAt < end.getTime()).reduce((sum, item) => sum + item.amount, 0) }; }), [expenses]);
  const sevenDaySpend = spendData.reduce((sum, item) => sum + item.value, 0);
  const monthSpend = expenses.filter((item) => { const date = new Date(item.createdAt), now = new Date(); return date.getMonth() === now.getMonth() && date.getFullYear() === now.getFullYear(); }).reduce((sum, item) => sum + item.amount, 0);
  const bodyChart: Array<{ day: string; weight: number }> = [];
  const monthlyAvailable = Math.max(0, wellness.monthlyBudget - monthSpend);
  const estimatedSavings = Math.max(0, monthlyAvailable);
  const todaySpend = spendData.at(-1)?.value || 0;
  const available = Math.max(0, wellness.allowance - todaySpend);
  const allowanceUsed = wellness.allowance ? todaySpend / wellness.allowance * 100 : 0;
  const nextRoutine = todayRoutines.find((item) => !item.done);
  const syncLabel = data.mode === "cloud" ? "Cloud synced" : data.mode === "syncing" ? "Connecting…" : "Saved on device";
  const lightMode = wellness.theme === "light";
  const greeting = new Date().getHours() < 12 ? "Good morning" : new Date().getHours() < 18 ? "Good afternoon" : "Good evening";
  const momentumScore = Math.round((progress + wellness.protein / wellness.proteinGoal * 100 + wellness.water / wellness.waterGoal * 100) / 3);

  useEffect(() => {
    if (!wellness.notificationsEnabled || notifications.permission !== "granted") return;
    const notifyDueItems = () => {
      const now = new Date();
      const currentTime = `${String(now.getHours()).padStart(2, "0")}:${String(now.getMinutes()).padStart(2, "0")}`;
      routines.filter((item) => (!item.days || item.days.includes(now.getDay())) && !item.done && item.time === currentTime).forEach((item) => {
        const key = `ascend:reminder:${now.toDateString()}:${item.id}`;
        if (!sessionStorage.getItem(key) && notifications.show("Routine time", `${item.title} is ready now.`)) sessionStorage.setItem(key, "1");
      });
      if (["10:00", "14:00", "18:00"].includes(currentTime) && wellness.water < wellness.waterGoal) {
        const key = `ascend:hydrate:${now.toDateString()}:${currentTime}`;
        if (!sessionStorage.getItem(key) && notifications.show("Hydration check", `You are at ${wellness.water}/${wellness.waterGoal} glasses today.`)) sessionStorage.setItem(key, "1");
      }
    };
    notifyDueItems();
    const interval = window.setInterval(notifyDueItems, 30_000);
    return () => window.clearInterval(interval);
  }, [notifications, routines, wellness.notificationsEnabled, wellness.water, wellness.waterGoal]);

  const run = async (action: () => Promise<void>, success: string) => { try { await action(); setNotice(success); } catch (cause) { setNotice(cause instanceof Error ? cause.message : "Something went wrong."); } window.setTimeout(() => setNotice(""), 2400); };
  const submitExpense = (event: FormEvent) => { event.preventDefault(); const input = expenseInput.trim(); const match = input.match(/(\d+(?:[.,]\d{1,2})?)(?!.*\d)/); const amount = match ? Number(match[1].replace(",", ".")) : 0; const description = match ? input.replace(match[0], "").replace(/\bRM\b/gi, "").trim() : ""; if (!description || !amount) return setNotice("Try: Lunch 18.50"); void run(() => data.addExpense(description, amount, expenseCategory), "Expense added"); setExpenseInput(""); };
  const submitRoutine = (event: FormEvent) => { event.preventDefault(); if (!routineDraft?.title.trim()) return; const payload = { time: routineDraft.time, title: routineDraft.title.trim(), meta: routineDraft.meta.trim() || "Personal routine block", days: routineDraft.days }; void run(() => routineDraft.id ? data.updateRoutine(routineDraft.id, payload) : data.createRoutine(payload), routineDraft.id ? "Routine updated" : "Routine created"); setRoutineDraft(null); };
  const submitLift = (event: FormEvent) => { event.preventDefault(); const weight = Number(liftDraft.weight), reps = Number(liftDraft.reps); if (!liftDraft.exercise.trim() || weight <= 0 || reps <= 0) return setNotice("Enter a valid exercise, weight and reps."); void run(() => data.addLift(liftDraft.exercise.trim(), weight, reps), "Workout set logged"); };
  const submitBody = (event: FormEvent) => { event.preventDefault(); setNotice("Body check-ins have been removed from Ascend OS."); };
  const editRoutine = (item: Routine) => setRoutineDraft({ id: item.id, time: item.time, title: item.title, meta: item.meta, days: item.days || [0, 1, 2, 3, 4, 5, 6] });

  return <div className={`ascend-app min-h-screen bg-[#070a0f] text-slate-100 selection:bg-emerald-400/30 ${lightMode ? "ascend-light" : "ascend-dark"}`}>
    <div className="ambient ambient-one" /><div className="ambient ambient-two" />
    <AnimatePresence>{notice && <motion.div initial={{ opacity: 0, y: -12 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} className="fixed left-1/2 top-4 z-[80] -translate-x-1/2 rounded-xl border border-white/10 bg-[#121923]/95 px-4 py-3 text-sm shadow-2xl backdrop-blur-xl"><span className="mr-2 text-emerald-300">●</span>{notice}</motion.div>}</AnimatePresence>

    <aside className="fixed inset-y-0 left-0 z-40 hidden w-[244px] border-r border-white/[0.06] bg-[#080c12]/90 px-5 py-6 backdrop-blur-xl lg:flex lg:flex-col">
      <a href="#command" className="flex items-center gap-3 px-2"><div className="grid h-9 w-9 place-items-center rounded-xl border border-emerald-300/20 bg-emerald-300/10 text-emerald-300"><Command size={18} /></div><div><div className="text-[15px] font-semibold">ASCEND <span className="text-emerald-300">OS</span></div><div className="text-[10px] uppercase tracking-[.22em] text-slate-600">Personal system</div></div></a>
      <nav className="mt-12 space-y-2">{nav.map((item) => { const Icon = item.icon, selected = active === item.label; return <a key={item.label} href={item.href} onClick={() => setActive(item.label)} className={`group flex h-11 items-center gap-3 rounded-xl px-3 text-sm transition ${selected ? "bg-white/[0.06] text-white" : "text-slate-500 hover:bg-white/[0.035] hover:text-slate-200"}`}><Icon size={18} className={selected ? "text-emerald-300" : "text-slate-600"} />{item.label}{selected && <motion.span layoutId="nav-dot" className="ml-auto h-1.5 w-1.5 rounded-full bg-emerald-300" />}</a>; })}</nav>
      <div className="mt-auto rounded-2xl border border-white/[0.06] bg-white/[0.025] p-4"><div className="mb-3 flex justify-between text-xs"><span className="text-slate-400">Daily ascent</span><span className="text-emerald-300">{progress}%</span></div><ProgressBar value={progress} /><p className="mt-3 flex items-center gap-2 text-xs text-slate-600">{data.mode === "cloud" ? <Cloud size={13} /> : <CloudOff size={13} />}{syncLabel}</p></div>
      <button onClick={() => setProfileOpen((value) => !value)} className="mt-4 flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm text-slate-500 hover:bg-white/[0.04]"><Settings size={17} /> Account & sync</button>
    </aside>

    <main className="relative z-10 pb-28 lg:ml-[244px] lg:pb-12">
      <header className="sticky top-0 z-30 flex h-[72px] items-center justify-between border-b border-white/[0.055] bg-[#070a0f]/80 px-5 backdrop-blur-xl sm:px-8 lg:px-10"><div className="flex items-center gap-3 lg:hidden"><div className="grid h-9 w-9 place-items-center rounded-xl bg-emerald-300/10 text-emerald-300"><Command size={18} /></div><span className="text-sm font-semibold">ASCEND OS</span></div><div className="hidden items-center gap-2 text-xs text-slate-500 lg:flex"><span className={`h-2 w-2 rounded-full ${data.mode === "cloud" ? "bg-emerald-300" : "bg-amber-400"}`} />{syncLabel}</div><div className="flex items-center gap-2"><button className="icon-button" onClick={() => document.getElementById("blueprint")?.scrollIntoView({ behavior: "smooth" })}><Search size={17} /></button><button className="icon-button" aria-label="Notification settings" onClick={() => setNotificationOpen(true)}><Bell size={17} />{(data.error || wellness.notificationsEnabled) && <span className={`absolute right-2 top-2 h-1.5 w-1.5 rounded-full ${data.error ? "bg-amber-400" : "bg-emerald-300"}`} />}</button><button className="icon-button" aria-label={`Switch to ${lightMode ? "dark" : "light"} mode`} title={`Switch to ${lightMode ? "dark" : "light"} mode`} onClick={() => void data.updateWellness({ theme: lightMode ? "dark" : "light" })}>{lightMode ? <Moon size={17} /> : <SunMedium size={17} />}</button><div className="relative"><button onClick={() => setProfileOpen((value) => !value)} className="ml-1 grid h-9 w-9 place-items-center rounded-xl border border-white/10 bg-slate-800 text-slate-300"><UserRound size={17} /></button>{profileOpen && <div className="absolute right-0 top-12 w-72 rounded-2xl border border-white/10 bg-[#10161f] p-4 shadow-2xl"><p className="text-sm font-medium">Account & cloud sync</p><p className="mt-1 break-all text-xs text-slate-500">{data.user?.email || (data.user?.isAnonymous ? "Private guest session" : "Device-only mode")}</p><div className="mt-4 rounded-xl bg-white/[0.03] p-3 text-xs leading-relaxed text-slate-500">{data.mode === "cloud" ? "Firebase is protecting and syncing your data." : "Add Firebase environment values to enable cloud sync."}</div>{data.user?.isAnonymous ? <button onClick={() => void run(data.connectGoogle, "Google account connected")} className="primary-button mt-3 w-full justify-center"><LogIn size={15} /> Continue with Google</button> : data.user ? <button onClick={() => void run(data.disconnect, "Signed out")} className="secondary-button mt-3 w-full"><LogOut size={15} /> Sign out</button> : null}</div>}</div></div></header>

      <div className="mx-auto max-w-[1480px] px-5 py-7 sm:px-8 lg:px-10 lg:py-9">
        {data.error && <div className="mb-5 rounded-xl border border-amber-400/15 bg-amber-400/[.06] px-4 py-3 text-xs text-amber-200">Cloud sync needs attention: {data.error}</div>}
        <section id="command" className="scroll-mt-24"><div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-2 flex items-center gap-2 text-xs uppercase tracking-[.18em] text-slate-600"><span className="social-dot" />{date}</p><h1 className="text-3xl font-semibold tracking-[-.055em] text-white sm:text-5xl">{greeting}. <span className="text-gradient">You’re on.</span></h1><p className="mt-2 text-sm text-slate-500">Small moves today. Big life energy later.</p></div><button onClick={() => document.getElementById("blueprint")?.scrollIntoView({ behavior: "smooth" })} className="primary-button self-start"><Zap size={15} /> Lock in next block</button></div>
          <div className="grid gap-4 xl:grid-cols-[1.05fr_1.05fr_.9fr]">
            <Panel className="relative overflow-hidden p-5 sm:p-6"><div className="card-shine" /><div className="relative flex h-full min-h-[184px] flex-col justify-between"><div className="flex justify-between"><div><p className="eyebrow">Available today</p><p className="mt-3 text-4xl font-semibold text-white">RM {money(available)}</p></div><div className="icon-well text-emerald-300"><CircleDollarSign size={19} /></div></div><div><div className="mb-2 flex justify-between text-xs"><span className="text-slate-500">Daily allowance</span><span className="text-slate-300">{Math.round(allowanceUsed)}% used</span></div><ProgressBar value={allowanceUsed} /><div className="mt-3 flex items-center justify-between"><span className="text-xs text-slate-600">RM {money(todaySpend)} spent</span><label className="text-xs text-slate-500">Limit RM <input type="number" value={wellness.allowance} onChange={(e) => void data.updateWellness({ allowance: Math.max(0, Number(e.target.value)) })} className="w-16 rounded-md border border-white/10 bg-white/[.03] px-1 py-1 text-right text-slate-300" /></label></div></div></div></Panel>
            <Panel className="p-5 sm:p-6"><div className="flex h-full min-h-[184px] flex-col justify-between"><div className="flex justify-between"><div><p className="eyebrow">Next routine block</p><p className="mt-3 text-2xl font-semibold">{nextRoutine?.title || "Day complete"}</p><p className="mt-2 text-sm text-slate-500">{nextRoutine ? `${nextRoutine.time} · ready when you are` : "Every block is secured"}</p></div><div className="icon-well text-blue-400"><CalendarDays size={19} /></div></div>{nextRoutine && <button onClick={() => void data.updateRoutine(nextRoutine.id, { done: true })} className="flex items-center justify-between rounded-xl border border-white/[.06] bg-white/[.025] px-4 py-3 text-sm text-slate-300"><span>{nextRoutine.meta}</span><ChevronRight size={16} /></button>}</div></Panel>
            <Panel className="flex min-h-[184px] items-center justify-between p-6"><div><p className="eyebrow">Daily completion</p><p className="mt-4 text-xl font-semibold">{progress === 100 ? "Complete" : "On pace"}</p><p className="mt-2 text-sm text-slate-500">{completed} of {todayRoutines.length} blocks secured.</p></div><div className="relative grid h-32 w-32 place-items-center"><svg className="h-full w-full -rotate-90" viewBox="0 0 120 120"><circle cx="60" cy="60" r="50" fill="none" stroke="rgba(255,255,255,.06)" strokeWidth="8" /><motion.circle cx="60" cy="60" r="50" fill="none" stroke="#36f4a2" strokeLinecap="round" strokeWidth="8" strokeDasharray="314" animate={{ strokeDashoffset: 314 - 314 * progress / 100 }} /></svg><span className="absolute text-2xl font-semibold">{progress}%</span></div></Panel>
          </div></section>

        <section className="mb-5 grid gap-4 lg:grid-cols-[1.15fr_.85fr]"><Panel className="pulse-card relative overflow-hidden p-5 sm:p-6"><div className="card-shine" /><div className="relative flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow text-emerald-300">Today’s energy</p><p className="mt-2 text-3xl font-semibold tracking-[-.045em] text-white">{momentumScore}% momentum</p><p className="mt-2 max-w-md text-sm text-slate-400">You don’t need a perfect day. Just protect the next promise you made to yourself.</p></div><div className="flex items-center gap-2"><div className="rounded-2xl border border-emerald-300/20 bg-emerald-300/10 px-3 py-2 text-right"><p className="text-[10px] uppercase tracking-[.15em] text-emerald-200/70">Current streak</p><p className="mt-1 text-lg font-semibold text-emerald-300"><Flame size={15} className="mr-1 inline text-orange-400" />{Math.max(...Object.values(wellness.habits).map((habit) => habit.streak))}</p></div><button onClick={() => document.getElementById("ascension")?.scrollIntoView({ behavior: "smooth" })} className="mini-add h-12 w-12"><ArrowUpRight size={19} /></button></div></div></Panel><div className="grid grid-cols-3 gap-3"><button onClick={() => document.getElementById("wealth")?.scrollIntoView({ behavior: "smooth" })} className="quick-action"><Banknote size={18} /><span>Add spend</span></button><button onClick={() => document.getElementById("blueprint")?.scrollIntoView({ behavior: "smooth" })} className="quick-action"><Target size={18} /><span>See plan</span></button><button onClick={() => void data.updateWellness({ protein: Math.min(wellness.proteinGoal, wellness.protein + 10) })} className="quick-action"><TrendingUp size={18} /><span>+10g protein</span></button></div></section>

        <section id="wealth" className="mt-5 scroll-mt-24 grid gap-5 xl:grid-cols-[1.35fr_.65fr]">
          <Panel className="min-w-0 p-5 sm:p-6"><div className="mb-6 flex justify-between"><div><p className="eyebrow">Wealth engine</p><h2 className="section-title">Seven-day spend</h2></div><span className="rounded-lg border border-white/[.06] px-3 py-2 text-xs text-slate-500">RM {money(sevenDaySpend)}</span></div><div className="h-[220px] min-w-0"><ResponsiveContainer width="100%" height="100%" minWidth={0} minHeight={220} initialDimension={{ width: 600, height: 220 }}><BarChart data={spendData}><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{ fill: "#667085", fontSize: 11 }} /><Tooltip cursor={{ fill: "rgba(255,255,255,.025)" }} contentStyle={{ background: "#10161f", border: "1px solid rgba(255,255,255,.08)", borderRadius: 12 }} formatter={(value) => [`RM ${money(Number(value))}`, "Spend"]} /><Bar dataKey="value" fill="#263242" radius={[7, 7, 2, 2]} activeBar={{ fill: "#36f4a2" }} /></BarChart></ResponsiveContainer></div></Panel>
          <Panel className="p-5 sm:p-6"><div className="flex justify-between"><div><p className="eyebrow">Quick capture</p><h2 className="section-title">Add expense</h2></div><div className="icon-well text-emerald-300"><Banknote size={18} /></div></div><form onSubmit={submitExpense} className="mt-7"><label className="mb-2 block text-xs text-slate-500">Description and amount</label><div className="flex gap-2"><input value={expenseInput} onChange={(e) => setExpenseInput(e.target.value)} className="field h-12 min-w-0 flex-1" placeholder="Lunch 18.50" /><button className="grid h-12 w-12 place-items-center rounded-xl bg-emerald-300 text-slate-950"><Plus size={20} /></button></div><select value={expenseCategory} onChange={(e) => setExpenseCategory(e.target.value as ExpenseCategory)} className="field mt-2 h-10">{expenseCategories.map((category) => <option key={category}>{category}</option>)}</select></form><div className="mt-4 space-y-2">{expenses.slice(0, 3).map((item) => <div key={item.id} className="flex items-center gap-3 rounded-xl bg-white/[.03] px-3 py-2.5 text-sm"><span className="min-w-0 flex-1 truncate">{item.description}</span><span className="rounded-md bg-white/[.05] px-1.5 py-0.5 text-[10px] text-slate-500">{item.category || "Other"}</span><span className="text-xs text-slate-500">RM {money(item.amount)}</span><button onClick={() => void data.deleteExpense(item.id)} className="text-slate-700 hover:text-rose-400"><Trash2 size={14} /></button></div>)}{expenses.length === 0 && <p className="rounded-xl border border-dashed border-white/[.07] p-4 text-center text-xs text-slate-600">Your first expense will appear here.</p>}</div></Panel>
        </section>

        <section className="mt-5 grid gap-5 md:grid-cols-2"><Panel className="p-5 sm:p-6"><div className="flex items-start justify-between"><div><p className="eyebrow">Monthly budget</p><h2 className="section-title">RM {money(monthlyAvailable)} remaining</h2></div><span className="text-xs text-slate-500">RM {money(monthSpend)} spent</span></div><div className="mt-6"><ProgressBar value={wellness.monthlyBudget ? monthSpend / wellness.monthlyBudget * 100 : 0} blue /><label className="mt-4 flex items-center justify-between text-xs text-slate-500">Monthly limit <span>RM <input type="number" value={wellness.monthlyBudget} onChange={(e) => void data.updateWellness({ monthlyBudget: Math.max(0, Number(e.target.value)) })} className="ml-1 w-24 rounded-md border border-white/10 bg-white/[.03] px-2 py-1 text-right text-slate-300" /></span></label></div></Panel><Panel className="p-5 sm:p-6"><p className="eyebrow">Savings goal</p><h2 className="section-title">RM {money(estimatedSavings)} / {money(wellness.savingsGoal)}</h2><div className="mt-6"><ProgressBar value={wellness.savingsGoal ? estimatedSavings / wellness.savingsGoal * 100 : 0} /><label className="mt-4 flex items-center justify-between text-xs text-slate-500">This month’s target <span>RM <input type="number" value={wellness.savingsGoal} onChange={(e) => void data.updateWellness({ savingsGoal: Math.max(0, Number(e.target.value)) })} className="ml-1 w-24 rounded-md border border-white/10 bg-white/[.03] px-2 py-1 text-right text-slate-300" /></span></label></div></Panel></section>

        <section id="blueprint" className="mt-5 scroll-mt-24 grid gap-5 xl:grid-cols-[1.25fr_.75fr]">
          <Panel className="p-5 sm:p-6"><div className="mb-7 flex justify-between"><div><p className="eyebrow">The blueprint</p><h2 className="section-title">Today’s timeline</h2></div><button onClick={() => setRoutineDraft(emptyRoutine)} className="secondary-button px-3"><Plus size={14} /> Add block</button></div><div className="space-y-1">{todayRoutines.map((item, index) => <motion.div layout key={item.id} className="group grid grid-cols-[48px_24px_1fr_auto] gap-3 rounded-xl px-2 py-3 hover:bg-white/[.025]"><span className="pt-1 text-xs text-slate-600">{item.time}</span><div className="relative flex justify-center"><Checkbox checked={item.done} onCheckedChange={() => void data.updateRoutine(item.id, { done: !item.done })} className="h-5 w-5 border-white/15 data-[state=checked]:bg-emerald-300 data-[state=checked]:text-slate-950" />{index < todayRoutines.length - 1 && <span className="absolute top-7 h-9 w-px bg-white/[.06]" />}</div><button onClick={() => void data.updateRoutine(item.id, { done: !item.done })} className="min-w-0 text-left"><span className={`block text-sm font-medium ${item.done ? "text-slate-600 line-through" : "text-slate-200"}`}>{item.title}</span><span className="mt-1 block truncate text-xs text-slate-600">{item.meta}</span></button><div className="flex gap-1 sm:opacity-0 sm:group-hover:opacity-100"><button onClick={() => editRoutine(item)} className="icon-button h-8 w-8"><Edit3 size={14} /></button><button onClick={() => window.confirm(`Delete “${item.title}”?`) && void data.deleteRoutine(item.id)} className="icon-button h-8 w-8 hover:text-rose-400"><Trash2 size={14} /></button></div></motion.div>)}</div></Panel>
          <Panel className="p-5 sm:p-6"><div className="flex justify-between"><div><p className="eyebrow">Core habits</p><h2 className="section-title">Streaks</h2></div><Flame size={20} className="text-orange-400" /></div><div className="mt-7 space-y-3">{habitDetails.map(({ key, name, icon: Icon }) => { const habit = wellness.habits[key]; return <button key={key} onClick={() => void data.toggleHabit(key)} className={`flex w-full items-center gap-3 rounded-2xl border p-4 text-left ${habit.completedToday ? "border-emerald-300/15 bg-emerald-300/[.04]" : "border-white/[.055] bg-white/[.022]"}`}><div className={`icon-well h-10 w-10 ${habit.completedToday ? "text-emerald-300" : "text-slate-400"}`}><Icon size={17} /></div><div className="flex-1"><p className="text-sm">{name}</p><p className="mt-1 text-xs text-slate-600">{habit.completedToday ? "Secured today" : "Tap to complete"}</p></div><div className="text-orange-400"><Flame size={14} className="inline" /> {habit.streak}<span className="block text-[10px] text-slate-600">days</span></div></button>; })}</div></Panel>
        </section>

        <section className="mt-5"><Panel className="overflow-x-auto p-5 sm:p-6"><div className="mb-5"><p className="eyebrow">Weekly planner</p><h2 className="section-title">Your recurring rhythm</h2></div><div className="grid min-w-[720px] grid-cols-7 gap-2">{weekDays.map((day, dayIndex) => <div key={day} className={`rounded-xl border p-3 ${dayIndex === weekday ? "border-emerald-300/30 bg-emerald-300/[.05]" : "border-white/[.06] bg-white/[.02]"}`}><p className={`mb-3 text-xs font-semibold ${dayIndex === weekday ? "text-emerald-300" : "text-slate-500"}`}>{day}</p><div className="space-y-2">{routines.filter((routine) => !routine.days || routine.days.includes(dayIndex)).sort((a, b) => a.time.localeCompare(b.time)).map((routine) => <button key={routine.id} onClick={() => editRoutine(routine)} className="block w-full rounded-lg bg-white/[.05] p-2 text-left hover:bg-white/[.09]"><span className="block text-[10px] text-slate-500">{routine.time}</span><span className="mt-1 block truncate text-xs text-slate-200">{routine.title}</span></button>)}{!routines.some((routine) => !routine.days || routine.days.includes(dayIndex)) && <p className="text-[10px] text-slate-700">Open space</p>}</div></div>)}</div></Panel></section>

        <section id="ascension" className="mt-5 scroll-mt-24"><div className="mb-4"><p className="eyebrow">Ascension protocol</p><h2 className="section-title">Build the next version</h2></div><div className="grid gap-5 xl:grid-cols-3">
          <Panel className="p-5 sm:p-6"><div className="flex justify-between"><div className="icon-well text-blue-400"><Dumbbell size={18} /></div><span className="text-xs text-slate-600">Physique</span></div><div className="mt-6 flex justify-between"><div><p className="text-sm text-slate-500">Protein intake</p><p className="mt-1 text-3xl font-semibold">{wellness.protein}<span className="text-base text-slate-600"> / {wellness.proteinGoal}g</span></p></div><span className="text-blue-400">{Math.round(wellness.protein / wellness.proteinGoal * 100)}%</span></div><div className="mt-4"><ProgressBar value={wellness.protein / wellness.proteinGoal * 100} blue /></div><div className="mt-4 flex gap-2"><button onClick={() => void data.updateWellness({ protein: Math.min(wellness.proteinGoal, wellness.protein + 10) })} className="secondary-button flex-1"><Plus size={14} /> Add 10g</button><button onClick={() => void data.updateWellness({ protein: 0 })} className="secondary-button px-4"><RotateCcw size={14} /></button></div><form onSubmit={submitLift} className="mt-5 border-t border-white/[.06] pt-4"><p className="mb-3 text-xs text-slate-500">Progressive overload log</p><input value={liftDraft.exercise} onChange={(e) => setLiftDraft({ ...liftDraft, exercise: e.target.value })} className="field h-10" /><div className="mt-2 grid grid-cols-[1fr_1fr_auto] gap-2"><input type="number" step=".5" value={liftDraft.weight} onChange={(e) => setLiftDraft({ ...liftDraft, weight: e.target.value })} className="field h-10" aria-label="Weight" /><input type="number" value={liftDraft.reps} onChange={(e) => setLiftDraft({ ...liftDraft, reps: e.target.value })} className="field h-10" aria-label="Reps" /><button className="grid h-10 w-10 place-items-center rounded-xl bg-blue-400 text-slate-950"><Plus size={17} /></button></div></form>{lifts[0] && <div className="mt-3 flex justify-between rounded-xl bg-white/[.025] p-3 text-sm"><span>{lifts[0].exercise} · {lifts[0].weight}kg × {lifts[0].reps}</span><button onClick={() => void data.deleteLift(lifts[0].id)}><Trash2 size={14} /></button></div>}</Panel>
          <Panel className="p-5 sm:p-6"><div className="flex justify-between"><div className="icon-well text-emerald-300"><HeartPulse size={18} /></div><span className="text-xs text-slate-600">Aesthetics</span></div><div className="mt-6"><div className="mb-3 flex justify-between"><div><p className="text-sm text-slate-500">Hydration</p><p className="mt-1 text-2xl font-semibold">{wellness.water}<span className="text-sm text-slate-600"> / {wellness.waterGoal} glasses</span></p></div><div className="flex gap-2"><button onClick={() => void data.updateWellness({ water: 0 })} className="mini-add"><RotateCcw size={13} /></button><button onClick={() => void data.updateWellness({ water: Math.min(wellness.waterGoal, wellness.water + 1) })} className="mini-add"><Plus size={14} /></button></div></div><ProgressBar value={wellness.water / wellness.waterGoal * 100} /></div><div className="mt-6 space-y-3">{([{ key: "skinMorning", label: "Morning skincare", icon: SunMedium }, { key: "skinNight", label: "Night skincare", icon: Moon }] as const).map((task) => { const Icon = task.icon; return <label key={task.key} className="flex cursor-pointer items-center gap-3 rounded-xl border border-white/[.055] p-3.5 text-sm"><Checkbox checked={wellness[task.key]} onCheckedChange={(checked) => void data.updateWellness({ [task.key]: checked === true })} className="border-white/15 data-[state=checked]:bg-emerald-300" /><Icon size={16} className="text-slate-600" />{task.label}</label>; })}</div></Panel>
          <Panel className="p-5 sm:p-6"><div className="flex justify-between"><div className="icon-well text-violet-400"><Brain size={18} /></div><span className="text-xs text-slate-600">Mental diet</span></div><label className="mt-6 block text-sm">What expanded you today?</label><p className="mt-1 text-xs text-slate-600">Capture one lesson or comfort-zone win.</p><textarea value={noteDraft} onChange={(e) => setNoteDraft(e.target.value)} className="field mt-4 min-h-[112px] resize-none py-3" placeholder="I learned that…" /><button onClick={() => void run(() => data.updateWellness({ note: noteDraft.trim() }), "Reflection saved")} disabled={!noteDraft.trim()} className="primary-button mt-3 w-full justify-center disabled:opacity-40">{wellness.note === noteDraft.trim() && wellness.note ? <><Check size={15} /> Saved</> : <><Sparkles size={15} /> Save reflection</>}</button></Panel>
        </div></section>
        <section className="mt-5"><Panel className="p-5 sm:p-6"><div className="flex items-center justify-between"><div><p className="eyebrow">Body progress</p><h2 className="section-title">Recomposition check-in</h2></div><span className="text-xs text-slate-500">{bodyLogs[0] ? `${bodyLogs[0].weight} kg latest` : "No check-ins yet"}</span></div><div className="mt-5 grid gap-5 lg:grid-cols-[1.25fr_.75fr]"><div className="h-[190px] min-w-0">{bodyChart.length > 1 ? <ResponsiveContainer width="100%" height="100%" minWidth={0}><LineChart data={bodyChart}><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{ fill: "#667085", fontSize: 11 }} /><Tooltip contentStyle={{ background: "#10161f", border: "1px solid rgba(255,255,255,.08)", borderRadius: 12 }} formatter={(value) => [`${value} kg`, "Weight"]} /><Line type="monotone" dataKey="weight" stroke="#37a8ff" strokeWidth={3} dot={{ fill: "#37a8ff", r: 3 }} /></LineChart></ResponsiveContainer> : <div className="grid h-full place-items-center rounded-xl border border-dashed border-white/[.08] text-xs text-slate-600">Log two weight check-ins to reveal your trend.</div>}</div><form onSubmit={submitBody} className="grid content-start gap-2"><label className="text-xs text-slate-500">Weight (kg)<input required type="number" step=".1" value={bodyDraft.weight} onChange={(e) => setBodyDraft({ ...bodyDraft, weight: e.target.value })} className="field mt-1 h-10" /></label><div className="grid grid-cols-2 gap-2"><label className="text-xs text-slate-500">Body fat %<input type="number" step=".1" value={bodyDraft.bodyFat} onChange={(e) => setBodyDraft({ ...bodyDraft, bodyFat: e.target.value })} className="field mt-1 h-10" /></label><label className="text-xs text-slate-500">Waist cm<input type="number" step=".1" value={bodyDraft.waist} onChange={(e) => setBodyDraft({ ...bodyDraft, waist: e.target.value })} className="field mt-1 h-10" /></label></div><button className="primary-button mt-1 justify-center"><Plus size={15} /> Save check-in</button></form></div>{bodyLogs[0] && <div className="mt-4 flex items-center justify-between rounded-xl bg-white/[.025] px-3 py-2 text-xs text-slate-500"><span>Latest: {bodyLogs[0].weight}kg{bodyLogs[0].bodyFat ? ` · ${bodyLogs[0].bodyFat}% fat` : ""}{bodyLogs[0].waist ? ` · ${bodyLogs[0].waist}cm waist` : ""}</span><button onClick={() => void data.deleteBodyLog(bodyLogs[0].id)} className="text-slate-600 hover:text-rose-400"><Trash2 size={14} /></button></div>}</Panel></section>
        <footer className="mt-8 flex justify-between border-t border-white/[.05] pt-6 text-xs text-slate-700"><span>Ascend OS · Private command center</span><span>{syncLabel}</span></footer>
      </div>
    </main>

    <nav className="fixed inset-x-4 bottom-4 z-50 grid grid-cols-4 rounded-2xl border border-white/[.08] bg-[#0c1119]/92 p-1.5 backdrop-blur-2xl lg:hidden">{nav.map((item) => { const Icon = item.icon; return <a key={item.label} href={item.href} onClick={() => setActive(item.label)} className={`flex flex-col items-center gap-1 rounded-xl py-2 text-[10px] ${active === item.label ? "bg-white/[.06] text-emerald-300" : "text-slate-600"}`}><Icon size={18} />{item.label}</a>; })}</nav>

    <AnimatePresence>{notificationOpen && <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-[70] grid place-items-center bg-black/70 p-4 backdrop-blur-sm" onMouseDown={(e) => e.target === e.currentTarget && setNotificationOpen(false)}><motion.div initial={{ scale: .96, y: 12 }} animate={{ scale: 1, y: 0 }} className="w-full max-w-md rounded-2xl border border-white/10 bg-[#0d131c] p-6"><div className="flex justify-between"><div><p className="eyebrow">Ascend alerts</p><h2 className="section-title">Phone notifications</h2></div><button onClick={() => setNotificationOpen(false)} className="icon-button"><X size={17} /></button></div><p className="mt-3 text-sm leading-relaxed text-slate-500">Routine alerts fire at the block time. Hydration checks run at 10:00, 14:00 and 18:00.</p><div className="mt-5 space-y-3"><button onClick={() => void run(async () => { await notifications.enable(); await data.updateWellness({ notificationsEnabled: true }); }, notifications.pushReady ? "Notifications and push are enabled" : "Notifications enabled while Ascend is open")} disabled={notifications.permission === "denied"} className="primary-button w-full justify-center disabled:opacity-40"><BellRing size={16} />{notifications.permission === "granted" ? "Notifications allowed" : notifications.permission === "denied" ? "Permission blocked in browser" : "Allow phone notifications"}</button><button onClick={() => void data.updateWellness({ notificationsEnabled: !wellness.notificationsEnabled })} className="secondary-button w-full"><Bell size={15} />{wellness.notificationsEnabled ? "Pause routine reminders" : "Turn on routine reminders"}</button><button onClick={() => void data.updateWellness({ notificationSound: !wellness.notificationSound })} className="secondary-button w-full">{wellness.notificationSound ? <Volume2 size={15} /> : <VolumeX size={15} />}{wellness.notificationSound ? "Sound on" : "Sound off"}</button><button onClick={() => { const shown = notifications.show("Ascend OS", "Your notification and sound test is working.", true); setNotice(shown ? "Test notification sent" : "Allow notifications first"); }} className="secondary-button w-full"><Zap size={15} /> Send a test notification</button></div><div className="mt-5 rounded-xl bg-white/[0.03] p-3 text-xs leading-relaxed text-slate-500">{notifications.pushReady ? "Push receiver is ready. Background alerts are delivered when your notification service sends them." : "For background alerts after the app is closed, add a Firebase Web Push certificate (VAPID key) in Cloudflare."}</div></motion.div></motion.div>}</AnimatePresence>
    <AnimatePresence>{routineDraft && <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-[70] grid place-items-center bg-black/70 p-4 backdrop-blur-sm" onMouseDown={(e) => e.target === e.currentTarget && setRoutineDraft(null)}><motion.form onSubmit={submitRoutine} initial={{ scale: .96, y: 12 }} animate={{ scale: 1, y: 0 }} className="w-full max-w-md rounded-2xl border border-white/10 bg-[#0d131c] p-6"><div className="flex justify-between"><div><p className="eyebrow">Blueprint editor</p><h2 className="section-title">{routineDraft.id ? "Edit routine block" : "Create routine block"}</h2></div><button type="button" onClick={() => setRoutineDraft(null)} className="icon-button"><X size={17} /></button></div><div className="mt-6 grid gap-4"><label className="text-xs text-slate-500">Time<input required type="time" value={routineDraft.time} onChange={(e) => setRoutineDraft({ ...routineDraft, time: e.target.value })} className="field mt-2 h-11" /></label><label className="text-xs text-slate-500">Title<input required autoFocus value={routineDraft.title} onChange={(e) => setRoutineDraft({ ...routineDraft, title: e.target.value })} className="field mt-2 h-11" /></label><label className="text-xs text-slate-500">Details<input value={routineDraft.meta} onChange={(e) => setRoutineDraft({ ...routineDraft, meta: e.target.value })} className="field mt-2 h-11" /></label><div><p className="text-xs text-slate-500">Repeat on</p><div className="mt-2 grid grid-cols-7 gap-1">{weekDays.map((day, index) => <button type="button" key={day} onClick={() => setRoutineDraft({ ...routineDraft, days: routineDraft.days.includes(index) ? routineDraft.days.filter((value) => value !== index) : [...routineDraft.days, index].sort() })} className={`rounded-lg py-2 text-[10px] ${routineDraft.days.includes(index) ? "bg-emerald-300 text-slate-950" : "bg-white/[.05] text-slate-500"}`}>{day}</button>)}</div></div></div><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={() => setRoutineDraft(null)} className="secondary-button px-4">Cancel</button><button className="primary-button"><Check size={15} /> Save block</button></div></motion.form></motion.div>}</AnimatePresence>
  </div>;
}
