"use client";

import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { Banknote, Bell, Brain, CalendarDays, Check, ChevronRight, CircleDollarSign, Cloud, CloudOff, Command, Dumbbell, Edit3, Flame, HeartPulse, Home, LogIn, LogOut, Moon, Plus, RotateCcw, Search, Settings, ShieldCheck, Sparkles, SunMedium, Trash2, UserRound, WalletCards, X, Zap } from "lucide-react";
import { Bar, BarChart, ResponsiveContainer, Tooltip, XAxis } from "recharts";
import { Checkbox } from "@/components/ui/checkbox";
import { type HabitKey, type Routine, useAscendData } from "@/hooks/use-ascend-data";

const nav = [{ label: "Command", icon: Home, href: "#command" }, { label: "Wealth", icon: WalletCards, href: "#wealth" }, { label: "Blueprint", icon: CalendarDays, href: "#blueprint" }, { label: "Ascension", icon: Sparkles, href: "#ascension" }];
const habitDetails: Array<{ key: HabitKey; name: string; icon: typeof Dumbbell }> = [{ key: "training", name: "Training", icon: Dumbbell }, { key: "deepWork", name: "Deep work", icon: Brain }, { key: "noSpend", name: "No-spend", icon: ShieldCheck }];
const emptyRoutine = { time: "08:00", title: "", meta: "" };
type RoutineDraft = typeof emptyRoutine & { id?: string };

function Panel({ children, className = "" }: { children: ReactNode; className?: string }) { return <section className={`panel ${className}`}>{children}</section>; }
function ProgressBar({ value, blue = false }: { value: number; blue?: boolean }) { const safe = Math.max(0, Math.min(100, value)); return <div className="h-2 overflow-hidden rounded-full bg-white/[0.06]" role="progressbar" aria-valuenow={Math.round(safe)}><motion.div initial={{ width: 0 }} animate={{ width: `${safe}%` }} className={`h-full rounded-full ${blue ? "bg-[#37a8ff] shadow-[0_0_18px_rgba(55,168,255,.5)]" : "bg-[#36f4a2] shadow-[0_0_18px_rgba(54,244,162,.45)]"}`} /></div>; }
const money = (value: number) => new Intl.NumberFormat("en-MY", { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(value);

export default function HomePage() {
  const data = useAscendData();
  const { routines, expenses, lifts, wellness } = data;
  const [active, setActive] = useState("Command");
  const [expenseInput, setExpenseInput] = useState("");
  const [routineDraft, setRoutineDraft] = useState<RoutineDraft | null>(null);
  const [liftDraft, setLiftDraft] = useState({ exercise: "Bench press", weight: "72.5", reps: "8" });
  const [noteDraft, setNoteDraft] = useState(wellness.note);
  const [notice, setNotice] = useState("");
  const [profileOpen, setProfileOpen] = useState(false);
  useEffect(() => setNoteDraft(wellness.note), [wellness.note]);
  const completed = routines.filter((item) => item.done).length;
  const progress = routines.length ? Math.round(completed / routines.length * 100) : 0;
  const date = useMemo(() => new Intl.DateTimeFormat("en", { weekday: "long", month: "long", day: "numeric" }).format(new Date()), []);
  const spendData = useMemo(() => Array.from({ length: 7 }, (_, index) => { const day = new Date(); day.setHours(0, 0, 0, 0); day.setDate(day.getDate() - (6 - index)); const end = new Date(day); end.setDate(end.getDate() + 1); return { day: index === 6 ? "Today" : new Intl.DateTimeFormat("en", { weekday: "short" }).format(day), value: expenses.filter((item) => item.createdAt >= day.getTime() && item.createdAt < end.getTime()).reduce((sum, item) => sum + item.amount, 0) }; }), [expenses]);
  const sevenDaySpend = spendData.reduce((sum, item) => sum + item.value, 0);
  const todaySpend = spendData.at(-1)?.value || 0;
  const available = Math.max(0, wellness.allowance - todaySpend);
  const allowanceUsed = wellness.allowance ? todaySpend / wellness.allowance * 100 : 0;
  const nextRoutine = routines.find((item) => !item.done);
  const syncLabel = data.mode === "cloud" ? "Cloud synced" : data.mode === "syncing" ? "Connecting…" : "Saved on device";

  const run = async (action: () => Promise<void>, success: string) => { try { await action(); setNotice(success); } catch (cause) { setNotice(cause instanceof Error ? cause.message : "Something went wrong."); } window.setTimeout(() => setNotice(""), 2400); };
  const submitExpense = (event: FormEvent) => { event.preventDefault(); const input = expenseInput.trim(); const match = input.match(/(\d+(?:[.,]\d{1,2})?)(?!.*\d)/); const amount = match ? Number(match[1].replace(",", ".")) : 0; const description = match ? input.replace(match[0], "").replace(/\bRM\b/gi, "").trim() : ""; if (!description || !amount) return setNotice("Try: Lunch 18.50"); void run(() => data.addExpense(description, amount), "Expense added"); setExpenseInput(""); };
  const submitRoutine = (event: FormEvent) => { event.preventDefault(); if (!routineDraft?.title.trim()) return; const payload = { time: routineDraft.time, title: routineDraft.title.trim(), meta: routineDraft.meta.trim() || "Personal routine block" }; void run(() => routineDraft.id ? data.updateRoutine(routineDraft.id, payload) : data.createRoutine(payload), routineDraft.id ? "Routine updated" : "Routine created"); setRoutineDraft(null); };
  const submitLift = (event: FormEvent) => { event.preventDefault(); const weight = Number(liftDraft.weight), reps = Number(liftDraft.reps); if (!liftDraft.exercise.trim() || weight <= 0 || reps <= 0) return setNotice("Enter a valid exercise, weight and reps."); void run(() => data.addLift(liftDraft.exercise.trim(), weight, reps), "Workout set logged"); };
  const editRoutine = (item: Routine) => setRoutineDraft({ id: item.id, time: item.time, title: item.title, meta: item.meta });

  return <div className="min-h-screen bg-[#070a0f] text-slate-100 selection:bg-emerald-400/30">
    <div className="ambient ambient-one" /><div className="ambient ambient-two" />
    <AnimatePresence>{notice && <motion.div initial={{ opacity: 0, y: -12 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} className="fixed left-1/2 top-4 z-[80] -translate-x-1/2 rounded-xl border border-white/10 bg-[#121923]/95 px-4 py-3 text-sm shadow-2xl backdrop-blur-xl"><span className="mr-2 text-emerald-300">●</span>{notice}</motion.div>}</AnimatePresence>

    <aside className="fixed inset-y-0 left-0 z-40 hidden w-[244px] border-r border-white/[0.06] bg-[#080c12]/90 px-5 py-6 backdrop-blur-xl lg:flex lg:flex-col">
      <a href="#command" className="flex items-center gap-3 px-2"><div className="grid h-9 w-9 place-items-center rounded-xl border border-emerald-300/20 bg-emerald-300/10 text-emerald-300"><Command size={18} /></div><div><div className="text-[15px] font-semibold">ASCEND <span className="text-emerald-300">OS</span></div><div className="text-[10px] uppercase tracking-[.22em] text-slate-600">Personal system</div></div></a>
      <nav className="mt-12 space-y-2">{nav.map((item) => { const Icon = item.icon, selected = active === item.label; return <a key={item.label} href={item.href} onClick={() => setActive(item.label)} className={`group flex h-11 items-center gap-3 rounded-xl px-3 text-sm transition ${selected ? "bg-white/[0.06] text-white" : "text-slate-500 hover:bg-white/[0.035] hover:text-slate-200"}`}><Icon size={18} className={selected ? "text-emerald-300" : "text-slate-600"} />{item.label}{selected && <motion.span layoutId="nav-dot" className="ml-auto h-1.5 w-1.5 rounded-full bg-emerald-300" />}</a>; })}</nav>
      <div className="mt-auto rounded-2xl border border-white/[0.06] bg-white/[0.025] p-4"><div className="mb-3 flex justify-between text-xs"><span className="text-slate-400">Daily ascent</span><span className="text-emerald-300">{progress}%</span></div><ProgressBar value={progress} /><p className="mt-3 flex items-center gap-2 text-xs text-slate-600">{data.mode === "cloud" ? <Cloud size={13} /> : <CloudOff size={13} />}{syncLabel}</p></div>
      <button onClick={() => setProfileOpen((value) => !value)} className="mt-4 flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm text-slate-500 hover:bg-white/[0.04]"><Settings size={17} /> Account & sync</button>
    </aside>

    <main className="relative z-10 pb-28 lg:ml-[244px] lg:pb-12">
      <header className="sticky top-0 z-30 flex h-[72px] items-center justify-between border-b border-white/[0.055] bg-[#070a0f]/80 px-5 backdrop-blur-xl sm:px-8 lg:px-10"><div className="flex items-center gap-3 lg:hidden"><div className="grid h-9 w-9 place-items-center rounded-xl bg-emerald-300/10 text-emerald-300"><Command size={18} /></div><span className="text-sm font-semibold">ASCEND OS</span></div><div className="hidden items-center gap-2 text-xs text-slate-500 lg:flex"><span className={`h-2 w-2 rounded-full ${data.mode === "cloud" ? "bg-emerald-300" : "bg-amber-400"}`} />{syncLabel}</div><div className="flex items-center gap-2"><button className="icon-button" onClick={() => document.getElementById("blueprint")?.scrollIntoView({ behavior: "smooth" })}><Search size={17} /></button><button className="icon-button" onClick={() => setNotice(data.error || syncLabel)}><Bell size={17} />{data.error && <span className="absolute right-2 top-2 h-1.5 w-1.5 rounded-full bg-amber-400" />}</button><div className="relative"><button onClick={() => setProfileOpen((value) => !value)} className="ml-1 grid h-9 w-9 place-items-center rounded-xl border border-white/10 bg-slate-800 text-slate-300"><UserRound size={17} /></button>{profileOpen && <div className="absolute right-0 top-12 w-72 rounded-2xl border border-white/10 bg-[#10161f] p-4 shadow-2xl"><p className="text-sm font-medium">Account & cloud sync</p><p className="mt-1 break-all text-xs text-slate-500">{data.user?.email || (data.user?.isAnonymous ? "Private guest session" : "Device-only mode")}</p><div className="mt-4 rounded-xl bg-white/[0.03] p-3 text-xs leading-relaxed text-slate-500">{data.mode === "cloud" ? "Firebase is protecting and syncing your data." : "Add Firebase environment values to enable cloud sync."}</div>{data.user?.isAnonymous ? <button onClick={() => void run(data.connectGoogle, "Google account connected")} className="primary-button mt-3 w-full justify-center"><LogIn size={15} /> Continue with Google</button> : data.user ? <button onClick={() => void run(data.disconnect, "Signed out")} className="secondary-button mt-3 w-full"><LogOut size={15} /> Sign out</button> : null}</div>}</div></div></header>

      <div className="mx-auto max-w-[1480px] px-5 py-7 sm:px-8 lg:px-10 lg:py-9">
        {data.error && <div className="mb-5 rounded-xl border border-amber-400/15 bg-amber-400/[.06] px-4 py-3 text-xs text-amber-200">Cloud sync needs attention: {data.error}</div>}
        <section id="command" className="scroll-mt-24"><div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-2 text-xs uppercase tracking-[.18em] text-slate-600">{date}</p><h1 className="text-3xl font-semibold tracking-[-.045em] text-white sm:text-4xl">Good morning.</h1><p className="mt-2 text-sm text-slate-500">Protect the momentum. Win the next block.</p></div><button onClick={() => document.getElementById("blueprint")?.scrollIntoView({ behavior: "smooth" })} className="primary-button self-start"><Zap size={15} /> Focus next block</button></div>
          <div className="grid gap-4 xl:grid-cols-[1.05fr_1.05fr_.9fr]">
            <Panel className="relative overflow-hidden p-5 sm:p-6"><div className="card-shine" /><div className="relative flex h-full min-h-[184px] flex-col justify-between"><div className="flex justify-between"><div><p className="eyebrow">Available today</p><p className="mt-3 text-4xl font-semibold text-white">RM {money(available)}</p></div><div className="icon-well text-emerald-300"><CircleDollarSign size={19} /></div></div><div><div className="mb-2 flex justify-between text-xs"><span className="text-slate-500">Daily allowance</span><span className="text-slate-300">{Math.round(allowanceUsed)}% used</span></div><ProgressBar value={allowanceUsed} /><div className="mt-3 flex items-center justify-between"><span className="text-xs text-slate-600">RM {money(todaySpend)} spent</span><label className="text-xs text-slate-500">Limit RM <input type="number" value={wellness.allowance} onChange={(e) => void data.updateWellness({ allowance: Math.max(0, Number(e.target.value)) })} className="w-16 rounded-md border border-white/10 bg-white/[.03] px-1 py-1 text-right text-slate-300" /></label></div></div></div></Panel>
            <Panel className="p-5 sm:p-6"><div className="flex h-full min-h-[184px] flex-col justify-between"><div className="flex justify-between"><div><p className="eyebrow">Next routine block</p><p className="mt-3 text-2xl font-semibold">{nextRoutine?.title || "Day complete"}</p><p className="mt-2 text-sm text-slate-500">{nextRoutine ? `${nextRoutine.time} · ready when you are` : "Every block is secured"}</p></div><div className="icon-well text-blue-400"><CalendarDays size={19} /></div></div>{nextRoutine && <button onClick={() => void data.updateRoutine(nextRoutine.id, { done: true })} className="flex items-center justify-between rounded-xl border border-white/[.06] bg-white/[.025] px-4 py-3 text-sm text-slate-300"><span>{nextRoutine.meta}</span><ChevronRight size={16} /></button>}</div></Panel>
            <Panel className="flex min-h-[184px] items-center justify-between p-6"><div><p className="eyebrow">Daily completion</p><p className="mt-4 text-xl font-semibold">{progress === 100 ? "Complete" : "On pace"}</p><p className="mt-2 text-sm text-slate-500">{completed} of {routines.length} blocks secured.</p></div><div className="relative grid h-32 w-32 place-items-center"><svg className="h-full w-full -rotate-90" viewBox="0 0 120 120"><circle cx="60" cy="60" r="50" fill="none" stroke="rgba(255,255,255,.06)" strokeWidth="8" /><motion.circle cx="60" cy="60" r="50" fill="none" stroke="#36f4a2" strokeLinecap="round" strokeWidth="8" strokeDasharray="314" animate={{ strokeDashoffset: 314 - 314 * progress / 100 }} /></svg><span className="absolute text-2xl font-semibold">{progress}%</span></div></Panel>
          </div></section>

        <section id="wealth" className="mt-5 scroll-mt-24 grid gap-5 xl:grid-cols-[1.35fr_.65fr]">
          <Panel className="min-w-0 p-5 sm:p-6"><div className="mb-6 flex justify-between"><div><p className="eyebrow">Wealth engine</p><h2 className="section-title">Seven-day spend</h2></div><span className="rounded-lg border border-white/[.06] px-3 py-2 text-xs text-slate-500">RM {money(sevenDaySpend)}</span></div><div className="h-[220px] min-w-0"><ResponsiveContainer width="100%" height="100%" minWidth={0} minHeight={220} initialDimension={{ width: 600, height: 220 }}><BarChart data={spendData}><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{ fill: "#667085", fontSize: 11 }} /><Tooltip cursor={{ fill: "rgba(255,255,255,.025)" }} contentStyle={{ background: "#10161f", border: "1px solid rgba(255,255,255,.08)", borderRadius: 12 }} formatter={(value) => [`RM ${money(Number(value))}`, "Spend"]} /><Bar dataKey="value" fill="#263242" radius={[7, 7, 2, 2]} activeBar={{ fill: "#36f4a2" }} /></BarChart></ResponsiveContainer></div></Panel>
          <Panel className="p-5 sm:p-6"><div className="flex justify-between"><div><p className="eyebrow">Quick capture</p><h2 className="section-title">Add expense</h2></div><div className="icon-well text-emerald-300"><Banknote size={18} /></div></div><form onSubmit={submitExpense} className="mt-7"><label className="mb-2 block text-xs text-slate-500">Description and amount</label><div className="flex gap-2"><input value={expenseInput} onChange={(e) => setExpenseInput(e.target.value)} className="field h-12 min-w-0 flex-1" placeholder="Lunch 18.50" /><button className="grid h-12 w-12 place-items-center rounded-xl bg-emerald-300 text-slate-950"><Plus size={20} /></button></div></form><div className="mt-4 space-y-2">{expenses.slice(0, 3).map((item) => <div key={item.id} className="flex items-center gap-3 rounded-xl bg-white/[.03] px-3 py-2.5 text-sm"><span className="min-w-0 flex-1 truncate">{item.description}</span><span className="text-xs text-slate-500">RM {money(item.amount)}</span><button onClick={() => void data.deleteExpense(item.id)} className="text-slate-700 hover:text-rose-400"><Trash2 size={14} /></button></div>)}{expenses.length === 0 && <p className="rounded-xl border border-dashed border-white/[.07] p-4 text-center text-xs text-slate-600">Your first expense will appear here.</p>}</div></Panel>
        </section>

        <section id="blueprint" className="mt-5 scroll-mt-24 grid gap-5 xl:grid-cols-[1.25fr_.75fr]">
          <Panel className="p-5 sm:p-6"><div className="mb-7 flex justify-between"><div><p className="eyebrow">The blueprint</p><h2 className="section-title">Today’s timeline</h2></div><button onClick={() => setRoutineDraft(emptyRoutine)} className="secondary-button px-3"><Plus size={14} /> Add block</button></div><div className="space-y-1">{routines.map((item, index) => <motion.div layout key={item.id} className="group grid grid-cols-[48px_24px_1fr_auto] gap-3 rounded-xl px-2 py-3 hover:bg-white/[.025]"><span className="pt-1 text-xs text-slate-600">{item.time}</span><div className="relative flex justify-center"><Checkbox checked={item.done} onCheckedChange={() => void data.updateRoutine(item.id, { done: !item.done })} className="h-5 w-5 border-white/15 data-[state=checked]:bg-emerald-300 data-[state=checked]:text-slate-950" />{index < routines.length - 1 && <span className="absolute top-7 h-9 w-px bg-white/[.06]" />}</div><button onClick={() => void data.updateRoutine(item.id, { done: !item.done })} className="min-w-0 text-left"><span className={`block text-sm font-medium ${item.done ? "text-slate-600 line-through" : "text-slate-200"}`}>{item.title}</span><span className="mt-1 block truncate text-xs text-slate-600">{item.meta}</span></button><div className="flex gap-1 sm:opacity-0 sm:group-hover:opacity-100"><button onClick={() => editRoutine(item)} className="icon-button h-8 w-8"><Edit3 size={14} /></button><button onClick={() => window.confirm(`Delete “${item.title}”?`) && void data.deleteRoutine(item.id)} className="icon-button h-8 w-8 hover:text-rose-400"><Trash2 size={14} /></button></div></motion.div>)}</div></Panel>
          <Panel className="p-5 sm:p-6"><div className="flex justify-between"><div><p className="eyebrow">Core habits</p><h2 className="section-title">Streaks</h2></div><Flame size={20} className="text-orange-400" /></div><div className="mt-7 space-y-3">{habitDetails.map(({ key, name, icon: Icon }) => { const habit = wellness.habits[key]; return <button key={key} onClick={() => void data.toggleHabit(key)} className={`flex w-full items-center gap-3 rounded-2xl border p-4 text-left ${habit.completedToday ? "border-emerald-300/15 bg-emerald-300/[.04]" : "border-white/[.055] bg-white/[.022]"}`}><div className={`icon-well h-10 w-10 ${habit.completedToday ? "text-emerald-300" : "text-slate-400"}`}><Icon size={17} /></div><div className="flex-1"><p className="text-sm">{name}</p><p className="mt-1 text-xs text-slate-600">{habit.completedToday ? "Secured today" : "Tap to complete"}</p></div><div className="text-orange-400"><Flame size={14} className="inline" /> {habit.streak}<span className="block text-[10px] text-slate-600">days</span></div></button>; })}</div></Panel>
        </section>

        <section id="ascension" className="mt-5 scroll-mt-24"><div className="mb-4"><p className="eyebrow">Ascension protocol</p><h2 className="section-title">Build the next version</h2></div><div className="grid gap-5 xl:grid-cols-3">
          <Panel className="p-5 sm:p-6"><div className="flex justify-between"><div className="icon-well text-blue-400"><Dumbbell size={18} /></div><span className="text-xs text-slate-600">Physique</span></div><div className="mt-6 flex justify-between"><div><p className="text-sm text-slate-500">Protein intake</p><p className="mt-1 text-3xl font-semibold">{wellness.protein}<span className="text-base text-slate-600"> / {wellness.proteinGoal}g</span></p></div><span className="text-blue-400">{Math.round(wellness.protein / wellness.proteinGoal * 100)}%</span></div><div className="mt-4"><ProgressBar value={wellness.protein / wellness.proteinGoal * 100} blue /></div><div className="mt-4 flex gap-2"><button onClick={() => void data.updateWellness({ protein: Math.min(wellness.proteinGoal, wellness.protein + 10) })} className="secondary-button flex-1"><Plus size={14} /> Add 10g</button><button onClick={() => void data.updateWellness({ protein: 0 })} className="secondary-button px-4"><RotateCcw size={14} /></button></div><form onSubmit={submitLift} className="mt-5 border-t border-white/[.06] pt-4"><p className="mb-3 text-xs text-slate-500">Progressive overload log</p><input value={liftDraft.exercise} onChange={(e) => setLiftDraft({ ...liftDraft, exercise: e.target.value })} className="field h-10" /><div className="mt-2 grid grid-cols-[1fr_1fr_auto] gap-2"><input type="number" step=".5" value={liftDraft.weight} onChange={(e) => setLiftDraft({ ...liftDraft, weight: e.target.value })} className="field h-10" aria-label="Weight" /><input type="number" value={liftDraft.reps} onChange={(e) => setLiftDraft({ ...liftDraft, reps: e.target.value })} className="field h-10" aria-label="Reps" /><button className="grid h-10 w-10 place-items-center rounded-xl bg-blue-400 text-slate-950"><Plus size={17} /></button></div></form>{lifts[0] && <div className="mt-3 flex justify-between rounded-xl bg-white/[.025] p-3 text-sm"><span>{lifts[0].exercise} · {lifts[0].weight}kg × {lifts[0].reps}</span><button onClick={() => void data.deleteLift(lifts[0].id)}><Trash2 size={14} /></button></div>}</Panel>
          <Panel className="p-5 sm:p-6"><div className="flex justify-between"><div className="icon-well text-emerald-300"><HeartPulse size={18} /></div><span className="text-xs text-slate-600">Aesthetics</span></div><div className="mt-6"><div className="mb-3 flex justify-between"><div><p className="text-sm text-slate-500">Hydration</p><p className="mt-1 text-2xl font-semibold">{wellness.water}<span className="text-sm text-slate-600"> / {wellness.waterGoal} glasses</span></p></div><div className="flex gap-2"><button onClick={() => void data.updateWellness({ water: 0 })} className="mini-add"><RotateCcw size={13} /></button><button onClick={() => void data.updateWellness({ water: Math.min(wellness.waterGoal, wellness.water + 1) })} className="mini-add"><Plus size={14} /></button></div></div><ProgressBar value={wellness.water / wellness.waterGoal * 100} /></div><div className="mt-6 space-y-3">{([{ key: "skinMorning", label: "Morning skincare", icon: SunMedium }, { key: "skinNight", label: "Night skincare", icon: Moon }] as const).map((task) => { const Icon = task.icon; return <label key={task.key} className="flex cursor-pointer items-center gap-3 rounded-xl border border-white/[.055] p-3.5 text-sm"><Checkbox checked={wellness[task.key]} onCheckedChange={(checked) => void data.updateWellness({ [task.key]: checked === true })} className="border-white/15 data-[state=checked]:bg-emerald-300" /><Icon size={16} className="text-slate-600" />{task.label}</label>; })}</div></Panel>
          <Panel className="p-5 sm:p-6"><div className="flex justify-between"><div className="icon-well text-violet-400"><Brain size={18} /></div><span className="text-xs text-slate-600">Mental diet</span></div><label className="mt-6 block text-sm">What expanded you today?</label><p className="mt-1 text-xs text-slate-600">Capture one lesson or comfort-zone win.</p><textarea value={noteDraft} onChange={(e) => setNoteDraft(e.target.value)} className="field mt-4 min-h-[112px] resize-none py-3" placeholder="I learned that…" /><button onClick={() => void run(() => data.updateWellness({ note: noteDraft.trim() }), "Reflection saved")} disabled={!noteDraft.trim()} className="primary-button mt-3 w-full justify-center disabled:opacity-40">{wellness.note === noteDraft.trim() && wellness.note ? <><Check size={15} /> Saved</> : <><Sparkles size={15} /> Save reflection</>}</button></Panel>
        </div></section>
        <footer className="mt-8 flex justify-between border-t border-white/[.05] pt-6 text-xs text-slate-700"><span>Ascend OS · Private command center</span><span>{syncLabel}</span></footer>
      </div>
    </main>

    <nav className="fixed inset-x-4 bottom-4 z-50 grid grid-cols-4 rounded-2xl border border-white/[.08] bg-[#0c1119]/92 p-1.5 backdrop-blur-2xl lg:hidden">{nav.map((item) => { const Icon = item.icon; return <a key={item.label} href={item.href} onClick={() => setActive(item.label)} className={`flex flex-col items-center gap-1 rounded-xl py-2 text-[10px] ${active === item.label ? "bg-white/[.06] text-emerald-300" : "text-slate-600"}`}><Icon size={18} />{item.label}</a>; })}</nav>

    <AnimatePresence>{routineDraft && <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-[70] grid place-items-center bg-black/70 p-4 backdrop-blur-sm" onMouseDown={(e) => e.target === e.currentTarget && setRoutineDraft(null)}><motion.form onSubmit={submitRoutine} initial={{ scale: .96, y: 12 }} animate={{ scale: 1, y: 0 }} className="w-full max-w-md rounded-2xl border border-white/10 bg-[#0d131c] p-6"><div className="flex justify-between"><div><p className="eyebrow">Blueprint editor</p><h2 className="section-title">{routineDraft.id ? "Edit routine block" : "Create routine block"}</h2></div><button type="button" onClick={() => setRoutineDraft(null)} className="icon-button"><X size={17} /></button></div><div className="mt-6 grid gap-4"><label className="text-xs text-slate-500">Time<input required type="time" value={routineDraft.time} onChange={(e) => setRoutineDraft({ ...routineDraft, time: e.target.value })} className="field mt-2 h-11" /></label><label className="text-xs text-slate-500">Title<input required autoFocus value={routineDraft.title} onChange={(e) => setRoutineDraft({ ...routineDraft, title: e.target.value })} className="field mt-2 h-11" /></label><label className="text-xs text-slate-500">Details<input value={routineDraft.meta} onChange={(e) => setRoutineDraft({ ...routineDraft, meta: e.target.value })} className="field mt-2 h-11" /></label></div><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={() => setRoutineDraft(null)} className="secondary-button px-4">Cancel</button><button className="primary-button"><Check size={15} /> Save block</button></div></motion.form></motion.div>}</AnimatePresence>
  </div>;
}
